# Generated by Django 2.2.9 on 2020-06-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookinghistory_amount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinghistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='roombooking',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rooms',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userdetails',
            table=None,
        ),
    ]
